### PR TITLE
Set default base url to be new image service

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Review by rowanmanning — APPROVED** [review]
Looks great 👍

**Comment by rowanmanning** [comment]
Let's merge after Image Service v2 has Nagios/Dashing set up, and we have the contract finalised

**Comment by JakeChampion** [comment]
Yup, after this is merged, we will need to update n-ui as that is the only repo which overrides the service-url. https://github.com/Financial-Times/n-ui/blob/5c90d86f510f18fea56a38ddcb6b53fa5368b271/icons/main.scss#L1

**Comment by rowanmanning** [comment]
We can merge now 👍

**Pull request merged**
