### PR TITLE
add eslint config to repo to integrate with text editors

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-icons bundle size difference from 6.0.2 to 9a26314edb13846612eb681cf693d5c7b40918f6
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-icons bundle size difference from 6.0.2 to eb13426bbcc15329c82603a0b3c62c2002d6960e
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-icons bundle size difference from 6.0.2 to 7df361103ea9600bfa08d55291d2a6415344bbfc
No significant bundle size differences found.

**Review by notlee — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
o-icons bundle size difference from 6.0.2 to 05c980f7e1abdee88463f18473cb405a6bd7fd81
No significant bundle size differences found.

**Pull request merged**
