### PR TITLE
add scroll-to icon

### PR DESCRIPTION
**Pull request by chee**
https://github.com/Financial-Times/fticons/pull/114

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-icons bundle size difference from 6.0.7 to 364c04457c94711f4803a34b188640cedcfa9741
css, master: 0.63kb increase (0.02kb/gzip)
css, internal: 0.63kb increase (0.02kb/gzip)
css, whitelabel: 0.63kb increase (0.02kb/gzip)

**Comment by origamiserviceuser** [comment]
o-icons bundle size difference from 6.0.7 to 00ce71d48428adaa94ffbe8c0657472e20ea8b9d
css, master: 0.63kb increase (0.02kb/gzip)
css, internal: 0.63kb increase (0.02kb/gzip)
css, whitelabel: 0.63kb increase (0.02kb/gzip)

**Comment by chee** [comment]
shall we merge?

**Review by JakeChampion — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
:tada: This PR is included in version v6.1.0 :tada:

**Comment by chee** [comment]
thank you @origamiserviceuser

**Pull request merged**
