### PR TITLE
Breaking

### PR DESCRIPTION
**Pull request by notlee**
**This is ready for a beta release.** Individual PRs have been approved,
but this is an opportunity to have a final scan before the beta.

See https://github.com/Financial-Times/o-icons/issues/85

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-icons bundle size difference from 5.11.2 to 888044d30970745095b7656df4301d9175be665f
css: 1.08kb increase (0.12kb/gzip)

**Comment by origamiserviceuser** [comment]
o-icons bundle size difference from 5.11.2 to b2111e0a238687cbab04e594b4239673f69d8e73
css: 1.08kb increase (0.12kb/gzip)

**Review by rowanmanning — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
o-icons bundle size difference from 5.11.2 to 1e9ec7e180671faccd97b023bb4133388e1c1f21
css: 1.08kb increase (0.12kb/gzip)

**Comment by origamiserviceuser** [comment]
o-icons bundle size difference from 5.11.2 to d12857f38b3344c76d68a497182e54fb6493b3d0
css: 1.08kb increase (0.12kb/gzip)

**Comment by origamiserviceuser** [comment]
o-icons bundle size difference from 5.11.2 to 37a6c2ae28920453002fd7406cdbd7adb5f153b7
css, master: 1.08kb increase (0.12kb/gzip)

**Comment by origamiserviceuser** [comment]
o-icons bundle size difference from 5.11.2 to 3a43093b20d7fa09c940eadf4d8bd70e8de0abdf
css, master: 1.08kb increase (0.12kb/gzip)

**Pull request merged**
